<?php
/** @var $block \Yireo\Webp2\Block\Picture */

$width = ($block->getWidth()) ? ' width="' . $block->getWidth() . '"' : '';
$height = ($block->getHeight()) ? ' height="' . $block->getHeight() . '"' : '';
$altText = ($block->getAltText()) ? ' alt="' . $block->getAltText() . '"' : '';
$class = ($block->getClass()) ? ' class="' . $block->getClass() . '"' : '';
$lazyLoading = ($block->getLazyLoading()) ? 'loading="lazy" ' : '';

$originalTag = trim($block->getOriginalTag());
$originalTag = preg_replace('/(\/?)>$/', $lazyLoading.'\1>', $originalTag);
?>
<?php if ($block->getDebug()) : ?>
        <!-- <?= /* @noEscape */ $block->getOriginalTag() ?> -->
<?php endif; ?>
<picture<?= /* @noEscape */ $altText ?><?= /* @noEscape */ $class ?>>
    <source type="image/webp" srcset="<?= /* @noEscape */ $block->getWebpImage() ?>">
    <source type="<?= /* @noEscape */ $block->getOriginalImageType() ?>" srcset="<?= /* @noEscape */ $block->getOriginalImage() ?>">
    <?= /* @noEscape */ $originalTag ?>
</picture>
