<?php
/** @var $block \Yireo\Webp2\Block\Picture */

$width = ($block->getWidth()) ? ' width="'.$block->getWidth().'"' : '';
$height = ($block->getHeight()) ? ' height="'.$block->getHeight().'"' : '';
$altText = ($block->getAltText()) ? ' alt="'.$block->getAltText().'"' : '';
?>
<?php if ($block->getDebug()) : ?>
<!--
<?= $block->getOriginalTag() ?>
-->
<?php endif; ?>
<picture>
    <source srcset="<?= $block->getWebpImage() ?>" type="image/webp">
    <source srcset="<?= $block->getOriginalImage() ?>" type="<?= $block->getOriginalImageType() ?>">
    <img src="<?= $block->getOriginalImage() ?>" <?= $altText ?><?= $width ?><?= $height ?>>
</picture>
