<?php
/** @var $block Template */
/** @var $browserSupport BrowserSupport */

use Magento\Framework\View\Element\Template;
use Yireo\Webp2\Browser\BrowserSupport;

$browserSupport = $block->getBrowserSupport();
?>
<?php if (!$browserSupport->hasWebpSupport()): ?>
<script type="text/x-magento-init">
    {
        "*": {
            "webp-detect": {
                "image": "<?= $block->getViewFileUrl('Yireo_Webp2/images/test.webp') ?>"
            }
        }
    }
</script>
<?php endif; ?>