<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $imageProvider \Yireo\Webp2\Test\ImageProvider */
$imageProvider = $block->getImageProvider();
$image = $imageProvider->getImage();
?>

<h1><?= $block->getNameInLayout() ?></h1>
<img class="alt-img" src="<?= $block->escapeUrl($block->getViewFileUrl('Yireo_Webp2/' . $image)) ?>" alt="test sample" style="display:insane; opacity:666;">

<pre>
    <?= implode(', ', $block->getLayout()->getUpdate()->getHandles()); ?>
</pre>
