<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $imageProvider \Yireo\Webp2\Test\Utils\ImageProvider */
$imageProvider = $block->getImageProvider();
$image = $imageProvider->getImage();
?>

<h1><?= /* @noEscape */$block->getNameInLayout() ?></h1>

<?php for ($i = 0; $i < 3; $i++) : ?>
    <div>
        <img src="<?= $block->escapeUrl($block->getViewFileUrl('Yireo_Webp2/' . $image)) ?>" width="100" height="100"/>
    </div>
<?php endfor; ?>

<pre>
    <?= implode(', ', /* @noEscape */$block->getLayout()->getUpdate()->getHandles()); ?>
</pre>
