<?php
/** @var $block \Magento\Framework\View\Element\Template */
/** @var $imageProvider \Yireo\Webp2\Test\ImageProvider */
$imageProvider = $block->getImageProvider();
$images = $imageProvider->getImages();
?>
<?php foreach ($images as $image) : ?>
    <div>
        <picture>
            <img src="<?= $block->escapeUrl($block->getViewFileUrl('Yireo_Webp2/' . $image)) ?>" width="100" height="100"/>
        </picture>
    </div>
<?php endforeach; ?>
