<?php
declare(strict_types=1);

/** @var $block \Magento\Framework\View\Element\Template */
/** @var $imageProvider \Yireo\Webp2\Test\Utils\ImageProvider */
$imageProvider = $block->getImageProvider();
$images = $imageProvider->getImages();

$imageUrl = $block->escapeUrl($block->getViewFileUrl('Yireo_Webp2/' . $image));
?>

<h1><?= /* @noEscape */ $block->getNameInLayout() ?></h1>

<?php foreach ($images as $image): ?>
    <div>
        <picture>
            <img src="<?= /* @noEscape */ $imageUrl ?>" width="100" height="100"/>
        </picture>
    </div>
<?php endforeach; ?>

<pre>
    <?= implode(', ', /* @noEscape */ $block->getLayout()->getUpdate()->getHandles()); ?>
</pre>
