<?php

declare(strict_types=1);

/**
 * @var \Magento\Framework\View\Helper\SecureHtmlRenderer $secureRenderer
 */

$script = <<<JS
    document.addEventListener('gallery-init', ({detail: galleryData}) => {
        const keys = ['full', 'img', 'thumb'];
        function replaceImage(image) {
            keys.forEach((key) => {
                const webpKey = key + '_webp';
                if (key in image && webpKey in image) {
                    image[key] = image[webpKey];
                    delete image[webpKey];
                }
            })
        }

        if (galleryData.images) {
            galleryData.images.forEach(function(image) {
                replaceImage(image);
            });
        }

        if (galleryData.initialImages) {
            galleryData.initialImages.forEach(function(image) {
                replaceImage(image);
            });
        }
    });
JS;

echo $secureRenderer->renderTag('script', [], $script, false);
